export const ModelActor = [
  {
    label: "Name",
    name: "name",
    value: "",
    type: "text",
    required: true,
  },
  {
    label: "Name birth",
    name: "name_birth",
    value: "",
    type: "text",
  },
  {
    label: "Nickname",
    name: "nickname",
    value: "",
    type: "text",
  },
  {
    label: "Name of country",
    name: "name_of_country",
    value: "",
    type: "text",
  },
  {
    label: "Name another",
    name: "name_another",
    value: "",
    type: "text",
  },
  {
    label: "Birthday",
    name: "birthday",
    value: "",
    type: "date",
  },
  {
    label: "Blood type",
    name: "blood_type",
    value: "",
    type: "text",
  },
  {
    label: "Height",
    name: "height",
    value: "",
    type: "number",
  },
  {
    label: "Weight",
    name: "weight",
    value: "",
    type: "number",
  },
  {
    label: "BWH",
    name: "bwh",
    value: "",
    type: "text",
  },
  {
    label: "Cup",
    name: "cup",
    value: "",
    type: "text",
  },
  {
    label: "Birthplace",
    name: "birthplace",
    value: "",
    type: "text",
  },
  {
    label: "Country",
    name: "country",
    value: "",
    type: "select",
  },
  {
    label: "Jobs",
    name: "jobs",
    value: "",
    type: "text",
  },
  {
    label: "Start at",
    name: "start_at",
    value: "",
    type: "date",
  },
  {
    label: "End at",
    name: "end_at",
    value: "",
    type: "date",
  },
  {
    label: "Website",
    name: "website",
    value: "",
    type: "text",
  },
  {
    label: "Link Onlyfans",
    name: "link_onlyfans",
    value: "",
    type: "text",
  },
  {
    label: "Link Tiktok",
    name: "link_tiktok",
    value: "",
    type: "text",
  },
  {
    label: "Link Youtube",
    name: "link_youtube",
    value: "",
    type: "text",
  },
  {
    label: "Link Instagram",
    name: "link_instagram",
    value: "",
    type: "text",
  },
  {
    label: "Link Twitter",
    name: "link_twitter",
    value: "",
    type: "text",
  },
  {
    label: "Link Telegram",
    name: "link_telegram",
    value: "",
    type: "text",
  },
];
export const ModelWebsite = [
  {
    label: "Name",
    name: "name",
    value: "",
    type: "text",
    required: true,
  },
  {
    label: "Path",
    name: "path",
    value: "",
    type: "text",
  },
]